suites:
  azure-specs:
    repo: https://github.com/Azure/azure-rest-api-specs
    branch: typespec-next
    pattern: "specification/**/tspconfig.yaml"
    entrypoints:
      - name: "client.tsp"
        options: ["--no-emit"]
      - name: "main.tsp"
  azure-specs-pr:
    repo: https://github.com/Azure/azure-rest-api-specs-pr
    branch: typespec-next
    pattern: "specification/**/tspconfig.yaml"
    entrypoints:
      - name: "client.tsp"
        options: ["--no-emit"]
      - name: "main.tsp"
