parameters:  
  "service-dir":
    default: "sdk/{{#toLowerCase}}{{folderName}}{{/toLowerCase}}"
  "dependencies":
    "additionalDirectories": []
    default: ""
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    ## emitter-output-dir: "{project-root}/.."
    examples-directory: "{project-root}/examples"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
  "@azure-tools/typespec-python":    
    package-dir: "{{#normalizePackageName}}{{parameters.ServiceNamespace}}{{/normalizePackageName}}"
    package-name: "{package-dir}"  
    package-mode: dataplane
  "@azure-tools/typespec-csharp":
    package-dir: "{{parameters.ServiceNamespace}}"
    namespace: "{package-dir}"
    clear-output-folder: true
    model-namespace: false
  "@azure-tools/typespec-ts":
    package-dir: "{{#normalizePackageName}}{{parameters.ServiceNamespace}}{{/normalizePackageName}}-rest"
    generateMetadata: true
    generateTest: true
    packageDetails:
      name: "@azure-rest/{{#normalizePackageName}}{{parameters.ServiceNamespace}}{{/normalizePackageName}}-rest"
      description: "{{parameters.ServiceNamespace}} Service"
  "@azure-tools/typespec-java":
    package-dir: "{{#normalizePackageName}}{{parameters.ServiceNamespace}}{{/normalizePackageName}}"
    namespace: com.{{#toLowerCase}}{{parameters.ServiceNamespace}}{{/toLowerCase}}
