parameters:
  "service-dir":
    default: "sdk/storage"
  "dependencies":
    default: ""
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    emitter-output-dir: "{project-root}/.."
    examples-dir: "{project-root}/examples"
    output-file: "{azure-resource-provider-folder}/Microsoft.BlobStorage/{version-status}/{version}/generated_blob.json"
  # Commented to avoid running emitter check on unconverted languages, uncomment when ready to use
  "@typespec/http-client-python":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-storage-blob/azure/storage/blob/_generated"
    package-name: "azure-storage-blob"
    package-mode: dataplane
    flavor: azure
  # "@azure-tools/typespec-csharp":
  #   emitter-output-dir: "{output-dir}/{service-dir}/{namespace}"
  #   namespace: "Azure.Storage.Blob"
  #   clear-output-folder: true
  #   model-namespace: false
  #   flavor: azure
  "@azure-tools/typespec-ts":
    emitter-output-dir: "{output-dir}/{service-dir}/storage-blob-rest"
    generate-metadata: true
    generate-test: true
    package-details:
      name: "@azure-rest/storage-blob"
      description: "Azure.Storage.Blob Service"
    flavor: azure
  # "@azure-tools/typespec-java":
  #   emitter-output-dir: "{output-dir}/{service-dir}/azure-storage-blob"
  #   namespace: com.azure.storage.blob
  #   flavor: azure
  "@azure-tools/typespec-rust":
    package-dir: "azure_storage_blob"
    crate-name: "azure_storage_blob"
    crate-version: "0.1.0"
    flavor: azure
    temp-omit-doc-links: true
  "@azure-tools/typespec-go":
    containing-module: "github.com/Azure/azure-sdk-for-go/sdk/storage/azblob"
    service-dir: "sdk/storage"
    emitter-output-dir: "{output-dir}/{service-dir}/azblob/internal/generated"
    generate-fakes: false
    omit-constructors: true
    go-generate: build.go
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/data-plane"
