emit:
  - '@azure-tools/typespec-autorest'
options:
  '@azure-tools/typespec-autorest':
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
    examples-directory: "{project-root}/examples"

