emit:
  - "@typespec/http-client-java"
options:
  "@typespec/http-client-java":
    emitter-output-dir: "{project-root}/tsp-output"
    dev-options:
      generate-code-model: true
      loglevel: info
      debug: false
      profile: false
